"""Constants for HelioZero integration."""

DOMAIN = "helio_zero"
CONF_HOST = "host"
CONF_API_TOKEN = "api_token"
CONF_INTEGRATION_MODE = "integration_mode"
CONF_SCAN_INTERVAL = "scan_interval"
CONF_SKIP_UNAVAILABLE_ON_FAILURE = "skip_unavailable_on_failure"
CONF_FAILURE_COUNT_UNTIL_UNAVAILABLE = "failure_count_until_unavailable"

MODE_COMPANION = "companion"
MODE_REST_ONLY = "rest_only"

DEFAULT_SCAN_INTERVAL = 30
MIN_SCAN_INTERVAL = 1
MAX_SCAN_INTERVAL = 300
DEFAULT_SKIP_UNAVAILABLE_ON_FAILURE = True
DEFAULT_FAILURE_COUNT_UNTIL_UNAVAILABLE = 10
MIN_FAILURE_COUNT_UNTIL_UNAVAILABLE = 0
MAX_FAILURE_COUNT_UNTIL_UNAVAILABLE = 1000

COMPANION_ENTITY_KEYS = frozenset({"republish_discovery"})
